Sales/urls.py
from django.conf.urls import url

from . import views

app_name = 'sales'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^makeinvoice/$', views.make_invoice, name='make_invoice'),
    url(r'^edit/(?P<invoice_id>(\d+))/$',views.edit, name='edit_invoice'),
    url(r'^edit/(?P<invoice_id>)/$', views.edit, name='edit_invoice'),
    url(r'^invoice/list/$', views.list_invoice, name='list_invoice'),
    # url(r'^dispatch/(?P<item_id>(\d+))/$',views.dispatch , name='dispatch_item')

    # url(r'^save/$', views.save, name='save'),
]

# url(r'^list/$', views.list , name='list'),
# #ex: /polls/5/
# url(r'^(?P<question_id>[0-9]+)/$',views.detail , name='detail'),
# # ex: /polls/5/results/
# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#  ex: /polls/5/vote/

Stock/urls.py
from django.conf.urls import url

from . import views

app_name = 'stock'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^received/$', views.received, name='received'),
    url(r'^receive/$', views.add_in_stock, name='add_in_stock'),
    url(r'^receive/(?P<item_id>(\d+))/$',views.add_in_stock , name='add_in_stock'),
    url(r'^dispatched/$', views.dispatched, name='dispatched'),
    url(r'^dispatch/$', views.dispatch, name='dispatch_item'),
    url(r'^dispatch/(?P<item_id>(\d+))/$',views.dispatch , name='dispatch_item'),
    url(r'^returned/$', views.returned, name='returned'),
    url(r'^return_item/$', views.return_item, name='return_item'),
    url(r'^return_item/(?P<item_id>(\d+))/$',views.return_item , name='return_item'),

    # url(r'^save/$', views.save, name='save'),
]

# url(r'^list/$', views.list , name='list'),
# #ex: /polls/5/
# url(r'^(?P<question_id>[0-9]+)/$',views.detail , name='detail'),
# # ex: /polls/5/results/
# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#  ex: /polls/5/vote/

hamroproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = (
    url(r'^stock/', include('Stock.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^cheque/', include('Cheque.urls')),
    url(r'^sales/', include('Sales.urls')),
    url(r'^admin/', admin.site.urls),
)

Sales/models.py
from __future__ import unicode_literals

from django.contrib.postgres.fields import ArrayField, JSONField
from django.db import models
from django.db import connection
from django.utils import timezone

# Create your models here.

from Stock.models import Item


class Invoice(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    number = models.IntegerField(unique=True)
    comment = models.TextField()
    issued_by = models.CharField(max_length=100)
    subtotal = models.FloatField()
    additional_charge = models.FloatField()
    total = models.FloatField()
    created_at = models.DateField(editable=False)
    updated_at = models.DateTimeField(default=timezone.now())
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)


    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Invoice, self).save(*args, **kwargs)

    def validate_data(self,invoice_data):
        for k,v in invoice_data.items():
            if (v == ''):
                raise EmptyValueException({"error_message": "Please enter all the values properly"})

        return

    @staticmethod
    def save_invoice(invoice_data,invoice=None):
        if(invoice == None):
            invoice = Invoice()

        invoice.name = invoice_data['client_name'] if invoice_data['client_name'] else ''
        invoice.address = invoice_data['client_address'] if invoice_data['client_address'] else ''
        invoice.number = invoice_data['invoice_number'] if invoice_data['invoice_number'] else ''
        invoice.comment = invoice_data['comment'] if invoice_data['comment'] else ''
        invoice.issued_by = invoice_data['issued_by'] if invoice_data['issued_by'] else ''
        invoice.date = invoice_data['date'] if invoice_data['date'] else ''
        invoice.subtotal = invoice_data['subtotal'] if invoice_data['subtotal'] else ''
        invoice.additional_charge = invoice_data['additional'] if invoice_data['additional'] else ''
        invoice.total = invoice_data['total'] if invoice_data['total'] else ''

        return invoice


class InvoiceDetail(models.Model):
    invoice = models.ForeignKey('Invoice', on_delete=models.CASCADE, related_name='detail')
    item = models.ForeignKey('Stock.Item', on_delete=models.CASCADE , related_name='stock')
    rate = models.FloatField()
    quantity = models.FloatField()
    amount = models.FloatField()
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateField(editable=False)
    updated_at = models.DateTimeField(default=timezone.now())

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(InvoiceDetail, self).save(*args, **kwargs)

    @staticmethod
    def save_invoice_detail(invoice_data , invoice):
        if invoice.detail.exists():
            all_details = invoice.detail.all().order_by('id')

        details = {}
        for i in range(1, 7):
            index = i - 1
            if invoice.detail.exists():   #if details of invoice exists
                if len(all_details) > index:   #  Number of invoice details in greater than index
                    detail = all_details[index]  #
                else:
                    detail = InvoiceDetail() #for new entry of invoice detail from edit
            else:
                detail = InvoiceDetail()  #for new invoice creation
            detail.invoice = invoice
            if invoice_data['item-'+str(i)] == '' or invoice_data['quantity-'+str(i)] == '' or invoice_data['rate-'+str(i)] == '' or invoice_data['total-'+str(i)] == '':
                break

            detail.item = Item.objects.get(pk=invoice_data['item-'+str(i)])
            detail.rate = invoice_data['rate-'+str(i)]
            detail.quantity = invoice_data['quantity-'+str(i)]
            detail.amount = invoice_data['total-'+str(i)]

            details[str(i)] = detail

        return details


class Sales:

    def dictfetchall(cursor):
        "Return all rows from a cursor as a dict"
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
            ]

    @staticmethod
    def get_sales(self,from_date, to_date):
        cursor = connection.cursor()
        query = """select a.item_id, a.item_name , a.sales_quantity , a.sales_amount , b.stock_quantity , b.stock_amount , b.stock_quantity - a.sales_quantity as remaining_quantity , a.sales_amount - b.stock_amount as profit from
        (
            select item.name as item_name, item.id as item_id , sum(sales.quantity) as sales_quantity, sum(sales.amount) as sales_amount
            from public."Stock_item" item
            inner join public."Sales_invoicedetail" sales
            on item.id = sales.item_id
            WHERE sales.created_at::date = %s
            group by item.id
        ) a
            inner join

        (
            select item.name as item_name, item.id as item_id, sum(incoming.quantity) as stock_quantity, sum(incoming.amount) as stock_amount from public."Stock_item" item
            left join public."Stock_incomingitem" incoming
            on item.id = incoming.code_id
            WHERE incoming.created_at::date = %s
            group by item.id
        )  b
        on a.item_id = b.item_id """;

        cursor.execute(query,from_date,to_date);
        row = self.dictfetchall(cursor)
        return row


class EmptyValueException(Exception):
    pass

Sales/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.template import loader

from Sales.models import Invoice, EmptyValueException, InvoiceDetail, Sales
from Stock.models import Item


def index(request):
    template = loader.get_template('sales/create_invoice.html')
    context = {

    }
    return HttpResponse(template.render(context, request));


def make_invoice(request):
    if (not request.POST):
        stock_items = Item.objects.all()

        template = loader.get_template('sales/create_invoice.html')

        context = {
            'stock_items': stock_items,
        }
        return HttpResponse(template.render(context, request));

    try:
        invoice = Invoice.save_invoice(request.POST, None)
        invoice.save()
        invoice_details = InvoiceDetail.save_invoice_detail(request.POST, invoice)


    except EmptyValueException as e:
        error = e.args[0]
        return render(request, 'sales/create_invoice.html', {
            'error_message': error["error_message"],
        })

    else:
        for invoice_detail in invoice_details.itervalues():
            invoice_detail.save()

    return HttpResponseRedirect(reverse('sales:make_invoice'));


def edit(request, invoice_id):
    try:
        if (not request.POST):
            stock_items = Item.objects.all()
            invoice = Invoice.objects.get(pk=invoice_id)
            if invoice.detail.exists():
                invoice_details = invoice.detail.all().order_by('id')
            else:
                invoice_details = ''

            template = loader.get_template('sales/edit_invoice.html')

            context = {
                'invoice_id': invoice_id,
                'stock_items': stock_items,
                'invoice': invoice,
                'invoice_details': invoice_details,
            }
            return HttpResponse(template.render(context, request))

        invoice_to_pass = Invoice.objects.get(pk=invoice_id)
        invoice = Invoice.save_invoice(request.POST, invoice_to_pass)
        invoice.save()
        invoice_details = InvoiceDetail.save_invoice_detail(request.POST, invoice)


    except EmptyValueException as e:
        error = e.args[0]
        return render(request, 'sales/edit_invoice.html', {
            'error_message': error["error_message"],
        })
    except Exception as ex:
        return HttpResponseRedirect(reverse('sales:make_invoice'));
        # return render(request, 'sales/create_invoice.html', {
        #     'error_message': ex,
        # })

    else:
        for invoice_detail in invoice_details.itervalues():
            invoice_detail.save()

    return HttpResponseRedirect(reverse('sales:make_invoice'));


def list_invoice(request):
    try:
        invoices = Invoice.objects.all().order_by('date').filter(is_active=True, is_deleted=False)

        template = loader.get_template('sales/list_invoice.html')

        context = {
            'invoices': invoices,
        }
    except Exception as e:
        return render(request, 'sales/list_invoice.html', {
            'error_message': e,
            'invoices': invoices,
        })

    return HttpResponse(template.render(context, request))


def delete_invoice(request, invoice_id):
    try:
        invoice = Invoice.objects.get(pk=invoice_id)
        if invoice.is_deleted is False:
            invoice.is_deleted = True
        else:
            invoice.is_deleted = False

        invoice.save()

        invoices = Invoice.objects.all().order_by('date').filter(is_active=True, is_deleted=False)

        template = loader.get_template('sales/list_invoice.html')

        context = {
            'invoices': invoices,
        }

    except Exception as e:
        invoices = Invoice.objects.all().order_by('date').filter(is_active=True, is_deleted=False)
        return render(request, 'sales/list_invoice.html', {
            'error_message': e,
            'invoices': invoices,
        })
    return HttpResponse(template.render(context, request))


def show_sales(request):
    try:
        if (not request.POST):
            sales = Sales.get_sales(from_date=None, to_date=None)
        else:
            from_date = request.POST['from_date'] if request.POST['from_date'] != '' else ''
            to_date = request.POST['to_date'] if request.POST['to_date'] != '' else ''
            sales = Sales.get_sales(from_date=from_date, to_date=to_date)
    except Exception as e:

    return sales

templates/sales/create_invoice.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form class="" method="post" action="{% url 'sales:make_invoice' %}">
    {% csrf_token %}
        <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="invoice-title">
                    <h2>Invoice</h2>
                </div>
                <hr>
                <div class="row">
                    <div class="col-xs-4">
                        <address>
                        <strong>Name:</strong><br>
                            <input type="text" class="form-control" name="client_name" placeholder="Full Name" required>
                             <strong>Address:</strong><br>
                            <input type="text" class="form-control" name="client_address" placeholder="Address"><br><br>
                        </address>
                    </div>
                    <div class="col-xs-4">
                        <address>
                        <strong>Issued By:</strong><br>
                            <input type="text" class="form-control" name="issued_by" placeholder="Full Name">
                        </address>
                    </div>
                    <div class="col-xs-4">
                        <address>
                            <strong>Comment:</strong><br>
                            <textarea name="comment"></textarea>
                        </address>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6 text-left">
                        <address>
                            <strong> Date:</strong><br>
                            <input id="date" type="date" name="date" required><br>
                        </address>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><strong>Invoice Number  <input type="number" name="invoice_number" required></strong></h4><br>

                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-condensed">
                                <thead>
                                    <tr>
                                        <td><strong>Particulars</strong></td>
                                        <td class="text-center"><strong>Quantity</strong></td>
                                        <td class="text-center"><strong>Rate</strong></td>
                                        <td class="text-right"><strong>Totals</strong></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <!-- foreach ($order->lineItems as $line) or some such thing here -->
                                    <div class="invoice_lines-1">
                                    <tr>
                                        <td>
                                            <select id="item" name="item-1" required>
                                                <option value="">Select Stock Item</option>
                                              {% for stock_item in stock_items %}
                                                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
                                              {% endfor %}
                                            </select>
                                        </td>
                                        <td class="text-center"><input type="number" step="any" id="quantity-1" name="quantity-1" required></td>
                                        <td class="text-center"><input type="number" step="any" name="rate-1" id="rate-1" required></td>
                                        <td class="text-right"><input type="number" step="any" name="total-1" id="total-1" required onfocus="update_total('1')"></td>
                                    </tr>
                                    </div>
                                    <div class="invoice_lines-2">
                                    <tr>
                                        <td>
                                            <select id="item" name="item-2">
                                                <option value="">Select Stock Item</option>
                                              {% for stock_item in stock_items %}
                                                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
                                              {% endfor %}
                                            </select>
                                        </td>
                                        <td class="text-center"><input type="number" step="any" id="quantity-2" name="quantity-2"></td>
                                        <td class="text-center"><input type="number" step="any" id="rate-2" name="rate-2"></td>
                                        <td class="text-right"><input type="number" step="any" id="total-2" name="total-2" onfocus="update_total(2)"></td>
                                    </tr>
                                    </div>
                                    <div class="invoice_lines-3">
                                    <tr>
                                        <td>
                                            <select id="item" name="item-3">
                                                <option value="">Select Stock Item</option>
                                              {% for stock_item in stock_items %}
                                                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
                                              {% endfor %}
                                            </select>
                                        </td>
                                        <td class="text-center"><input type="number" step="any" id="quantity-3" name="quantity-3"></td>
                                        <td class="text-center"><input type="number" step="any" name="rate-3" id="rate-3"></td>
                                        <td class="text-right"><input type="number" step="any" name="total-3" id="total-3" onfocus="update_total(3)"></td>
                                    </tr>
                                    </div>
                                    <div class="invoice_lines-4">
                                    <tr>
                                        <td>
                                            <select id="item" name="item-4">
                                                <option value="">Select Stock Item</option>
                                              {% for stock_item in stock_items %}
                                                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
                                              {% endfor %}
                                            </select>
                                        </td>
                                        <td class="text-center"><input type="number" step="any" id="quantity-4" name="quantity-4"></td>
                                        <td class="text-center"><input type="number" step="any" id="rate-4" name="rate-4"></td>
                                        <td class="text-right"><input type="number" step="any" id="total-4" name="total-4" onfocus="update_total(4)"></td>
                                    </tr>
                                    </div>
                                    <div class="invoice_lines-5">
                                    <tr>
                                        <td>
                                            <select id="item" name="item-5">
                                                <option value="">Select Stock Item</option>
                                              {% for stock_item in stock_items %}
                                                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
                                              {% endfor %}
                                            </select>
                                        </td>
                                        <td class="text-center"><input type="number" step="any" id="quantity-5" name="quantity-5"></td>
                                        <td class="text-center"><input type="number" step="any" id="rate-5" name="rate-5"></td>
                                        <td class="text-right"><input type="number" step="any" name="total-5" id="total-5" onfocus="update_total(5)"></td>
                                    </tr>
                                    </div>
                                    <div class="invoice_lines-6">
                                    <tr>
                                        <td>
                                            <select id="item" name="item-6">
                                                <option value="">Select Stock Item</option>
                                              {% for stock_item in stock_items %}
                                                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
                                              {% endfor %}
                                            </select>
                                        </td>
                                        <td class="text-center"><input type="number" step="any" id="quantity-6" name="quantity-6"></td>
                                        <td class="text-center"><input type="number" step="any" id="rate-6" name="rate-6"></td>
                                        <td class="text-right"><input type="number" step="any" id="total-6" name="total-6" onfocus="update_total(6)"></td>
                                    </tr>
                                    </div>
                                    <tr>
                                        <td class="thick-line"></td>
                                        <td class="thick-line"></td>
                                        <td class="thick-line text-center"><strong>Subtotal</strong></td>
                                        <td class="thick-line text-right"><input type="number" step="any" id="subtotal" name="subtotal" placeholder="SubTotal" required onclick="update_subtotal()"></td>
                                    </tr>
                                    <tr>
                                        <td class="no-line"></td>
                                        <td class="no-line"></td>
                                        <td class="no-line text-center"><strong>Additional Charge</strong></td>
                                        <td class="no-line text-right"><input type="number" step="any" id="additional" name="additional" placeholder="Additional Charge"></td>
                                    </tr>
                                    <tr>
                                        <td class="no-line"></td>
                                        <td class="no-line"><button type="submit" class="btn btn-success">Save</button></td>
                                        <td class="no-line text-center"><strong>Total</strong></td>
                                        <td class="no-line text-right"><input type="number" step="any" name="total" id="total" placeholder="Total" required onfocus="update_net_total()"></td>
                                        <td><button type="submit" class="btn btn-success">Save</button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
</body>
</html>

<script>

    $(document).ready(function() {
        var date = new Date();

        var day = date.getDate();
        var month = date.getMonth() + 1;
        var year = date.getFullYear();

        if (month < 10) month = "0" + month;
        if (day < 10) day = "0" + day;

        var today = year + "-" + month + "-" + day;
        $("#date").attr("value", today);
    });

    function update_total(element_id) {

        var total = document.getElementById('total-'+element_id);
        var quantity = document.getElementById('quantity-'+element_id);
        var rate   =   document.getElementById('rate-'+element_id);
        total.value = quantity.value*rate.value;
    }

    function update_subtotal() {
        var subtotal = document.getElementById('subtotal');
        var sub = 0;
        for (i = 1; i < 7; i++) {
             sub = sub + +document.getElementById('total-'+i).value;
        }
        subtotal.value = sub;
    }
    function update_net_total() {
        var total = document.getElementById('total');
        var subtotal = document.getElementById('subtotal').value;
        var additional = document.getElementById('additional').value;
        total.value = +subtotal + +additional;
    }

</script>

templates/sales/list_invoice.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Items</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <br>
    <br>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'sales:list_invoice' %}" class="form-inline col-lg-11 col-lg-offset-1" >
    <div class="form-group">
    <label for="search">Search Item</label>
    <input type="text" class="form-control" name="search" placeholder="Enter Search">
    <button type="submit" class="btn btn-default">Submit</button>
  </div>

</form>
<div class="clearfix"></div>
<br>
<div class="table-responsive col-lg-10 col-lg-offset-1">
<table  border="1" about="Stock" class="table" >
    <thead>
        <td><b>Invoice Number</b></td>
        <td><b>Invoice Name</b></td>
        <td><b>Invoice Date</b></td>
        <td><b>Address</b></td>
        <td><b>Issued By</b></td>
        <td><b>Total</b></td>
        <td><b>Actions</b></td>
    </thead>

    <tbody>
        {% if invoices %}
            {% for invoice in invoices%}
                <tr>
                    <td>{{invoice.number}}</td>
                    <td>{{invoice.name }}</td>
                    <td>{{invoice.date }}</td>
                    <td>{{invoice.address }}</td>
                    <td>{{invoice.issued_by }}</td>
                    <td>{{invoice.total }}</td>
                    <td>
                       <!-- Single button -->
                        <div class="btn-group">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'sales:edit_invoice' invoice.id %}">View Details</a></li>
{#                            <li><a href="{% url 'stock:dispatch_item' stock.id %}">Dispatch</a></li>#}
{#                            <li><a href="{% url 'stock:return_item' %}">Return</a></li>#}
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <div class="alert alert-info" role="alert"><p>No Stock.</p></div>

        {% endif %}
    </tbody>
</table>
</div>

</body>
</html>