Sales/urls.py
from django.conf.urls import url

from . import views

app_name = 'sales'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^makeinvoice/$', views.make_invoice, name='make_invoice'),
    url(r'^edit/(?P<invoice_id>(\d+))/$',views.edit, name='edit_invoice'),
    url(r'^edit/(?P<invoice_id>)/$', views.edit, name='edit_invoice'),
    url(r'^invoice/list/$', views.list_invoice, name='list_invoice'),
    # url(r'^dispatch/(?P<item_id>(\d+))/$',views.dispatch , name='dispatch_item')

    # url(r'^save/$', views.save, name='save'),
]

# url(r'^list/$', views.list , name='list'),
# #ex: /polls/5/
# url(r'^(?P<question_id>[0-9]+)/$',views.detail , name='detail'),
# # ex: /polls/5/results/
# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#  ex: /polls/5/vote/

Stock/urls.py
from django.conf.urls import url

from . import views

app_name = 'stock'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^received/$', views.received, name='received'),
    url(r'^receive/$', views.add_in_stock, name='add_in_stock'),
    url(r'^receive/(?P<item_id>(\d+))/$',views.add_in_stock , name='add_in_stock'),
    url(r'^dispatched/$', views.dispatched, name='dispatched'),
    url(r'^dispatch/$', views.dispatch, name='dispatch_item'),
    url(r'^dispatch/(?P<item_id>(\d+))/$',views.dispatch , name='dispatch_item'),
    url(r'^returned/$', views.returned, name='returned'),
    url(r'^return_item/$', views.return_item, name='return_item'),
    url(r'^return_item/(?P<item_id>(\d+))/$',views.return_item , name='return_item'),

    # url(r'^save/$', views.save, name='save'),
]

# url(r'^list/$', views.list , name='list'),
# #ex: /polls/5/
# url(r'^(?P<question_id>[0-9]+)/$',views.detail , name='detail'),
# # ex: /polls/5/results/
# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#  ex: /polls/5/vote/

hamroproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = (
    url(r'^stock/', include('Stock.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^cheque/', include('Cheque.urls')),
    url(r'^sales/', include('Sales.urls')),
    url(r'^admin/', admin.site.urls),
)

Stock/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=255, unique=True)
    identifier = models.CharField(max_length=100, blank=True)
    company = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    @staticmethod
    def save_stock(stock_data):

        stock = Item()
        for k,v in stock_data.items():
            if (v == ''):
                raise EmptyValueException({"error_message": "Please enter all the values properly"})

        stock.name = stock_data['stock_name']
        stock.identifier = stock_data['stock_identifier']
        stock.company = stock_data['stock_company']

        return stock


class IncomingItem(models.Model):
    code = models.ForeignKey('Item', on_delete=models.CASCADE,
                             related_name='+')
    quantity = models.FloatField()
    rate = models.FloatField()
    amount = models.FloatField()
    received_from = models.CharField(max_length=200)
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    @staticmethod
    def save_stock(data):

        item = IncomingItem()
        for k, v in data.items():
            print k
            if (v == ''):
                raise EmptyValueException({"error_message": "Please enter all the values properly"})

        item.code = Item.objects.get(pk = data['code'])
        item.quantity = data['quantity']
        item.rate = data['rate']
        item.amount = data['amount']
        item.received_from = data['received_from']

        return item


class DispatchingItem(models.Model):
    code = models.ForeignKey('Item', on_delete=models.CASCADE,
                             related_name='+')
    quantity = models.FloatField()
    rate = models.FloatField()
    amount = models.FloatField()
    comment = models.TextField()
    dispatched_to = models.CharField(max_length=255)
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    @staticmethod
    def dispatch(data):

        item = DispatchingItem()
        for k, v in data.items():
            if (v == ''):
                raise EmptyValueException({"error_message": "Please enter all the values properly"})

        item.code = Item.objects.get(pk=data['code'])
        item.quantity = data['quantity']
        item.rate = data['rate']
        item.amount = data['amount']
        item.comment = data['comment']
        item.dispatched_to = data['dispatched_to']

        return item


class ReturningItem(models.Model):
    code = models.ForeignKey('Item', on_delete=models.CASCADE, related_name='+')
    quantity = models.FloatField()
    returned_by = models.CharField(max_length=100)
    comment = models.TextField()
    damaged = models.BooleanField(default=False)
    date = models.DateField(auto_now=True)
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    @staticmethod
    def returned(data):

        item = ReturningItem()
        for k, v in data.items():
            if (v == ''):
                raise EmptyValueException({"error_message": "Please enter all the values properly"})

        item.code = Item.objects.get(pk=data['code'])
        item.quantity = data['quantity']
        item.returned_by = data['returned_by']
        item.comment = data['comment']
        item.damaged = data['damaged']

        return item


class EmptyValueException(Exception):
    pass

Stock/views.py
import re

from django.db.models import Q
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render

# Create your views here.
from django.template import loader

from Stock.models import Item, IncomingItem, DispatchingItem, ReturningItem
from Stock.models import EmptyValueException


def index(request):
    name = request.GET['stock_name'] if request.GET else ''
    stock_list = Item.objects.filter(Q(name__icontains=name.strip()) | Q(identifier__icontains=name.strip()))
    template = loader.get_template('stock/list_stock.html')
    context = {
        'stock_list': stock_list,

    }
    return HttpResponse(template.render(context, request));


def add(request):
    if (not request.POST):
        template = loader.get_template('stock/add_item.html')

        context = {

        }
        return HttpResponse(template.render(context, request));

    try:
        stock_data = {
            'stock_name': request.POST['stock_name'],
            'stock_identifier': request.POST['stock_identifier'],
            'stock_company': request.POST['stock_company'],
        }
        stock = Item.save_stock(stock_data)

    except EmptyValueException as e:
        error = e.args[0]
        return render(request, 'stock/add_item.html', {
            'error_message': error["error_message"],
        })

    else:
        stock.save()

    return HttpResponseRedirect(reverse('stock:index'));


def add_in_stock(request, item_id=''):
    if (not request.POST):
        stock_items = Item.objects.all()
        if (not item_id == ''):
            stock = Item.objects.get(pk=item_id)
        else:
            stock = ''
        template = loader.get_template('stock/add_stock.html')
        context = {
            'stock': stock,
            'stock_items': stock_items,
        }
        return HttpResponse(template.render(context, request));
    else:
        try:
            incoming_item = IncomingItem.save_stock(request.POST)

        except EmptyValueException as e:
            error = e.args[0]
            return render(request, 'stock/add_stock.html', {
                'error_message': error["error_message"],
            })

        else:
            incoming_item.save()

    return HttpResponseRedirect(reverse('stock:received'));


def received(request):
    code_id = request.GET['stock_id'] if request.GET else ''
    stock_items = Item.objects.all()
    if(code_id != ''):
        items = IncomingItem.objects.filter(code_id=code_id)
    else:
        items = IncomingItem.objects.all()
    template = loader.get_template('stock/incoming_item.html')
    context = {
        'items': items,
        'stock_items': stock_items,
    }
    return HttpResponse(template.render(context, request));


def dispatch(request, item_id=''):
    stock_items = Item.objects.all()
    if (not request.POST):
        if (not item_id == ''):
            stock = Item.objects.get(pk=item_id)
        else:
            stock = ''
        template = loader.get_template('stock/add_dispatch.html')
        context = {
            'stock': stock,
            'stock_items': stock_items,
        }
        return HttpResponse(template.render(context, request));
    else:
        try:
            dispatch_item = DispatchingItem.dispatch(request.POST)

        except EmptyValueException as e:
            error = e.args[0]
            return render(request, 'stock/add_dispatch.html', {
                'error_message': error["error_message"],
                'stock_items': stock_items,
            })

        else:
            dispatch_item.save()

    return HttpResponseRedirect(reverse('stock:dispatched'));


def dispatched(request):
    stock_id = request.GET['stock_id'] if request.GET else ''
    stock_items = Item.objects.all()
    if(stock_id != ''):
        items = DispatchingItem.objects.filter(code_id=stock_id)
    else:
        items = DispatchingItem.objects.all()
    template = loader.get_template('stock/dispached.html')
    context = {
        'items': items,
        'stock_items': stock_items,
    }
    return HttpResponse(template.render(context, request));


def returned(request):
    code_id = request.GET['stock_id'] if request.GET else ''
    stock_items = Item.objects.all()
    if(code_id != ''):
        items = ReturningItem.objects.filter(code_id=code_id)
    else:
        items = ReturningItem.objects.all()
    template = loader.get_template('stock/returned.html')
    context = {
        'items': items,
        'stock_items': stock_items,
    }
    return HttpResponse(template.render(context, request));


def return_item(request, item_id=''):
    stock_items = Item.objects.all()
    if (not request.POST):
        if (not item_id == ''):
            stock = Item.objects.get(pk=item_id)
        else:
            stock = ''
        template = loader.get_template('stock/add_returned.html')
        context = {
            'stock': stock,
            'stock_items': stock_items,
        }
        return HttpResponse(template.render(context, request));
    else:
        try:
            dispatch_item = ReturningItem.returned(request.POST)

        except EmptyValueException as e:
            error = e.args[0]
            return render(request, 'stock/add_returned.html', {
                'error_message': error["error_message"],
                'stock_items':stock_items,
            })

        else:
            dispatch_item.save()

    return HttpResponseRedirect(reverse('stock:returned'));

# def test (request):
#     f = open('assignment_find_sum.txt', 'r')
#     sum = 0
#     list_of_numbers = []
#     for line in f:
#         print line
#         list_of_numbers.extend(re.findall('[0-9.]+'), line)
#     for i, val in enumerate(list_of_numbers):
#         sum = sum + val
#
#     f.close()
#     return

# def test(request):
#     name = request.GET['stock_id'] if request.GET else ''
#     stock_items = Item.objects.filter(name__icontains=name)
#     items = IncomingItem.objects.all()
#     template = loader.get_template('stock/incoming_item.html')
#     context = {
#         'items': items,
#         'stock_items': stock_items,
#     }
#     return HttpResponse(template.render(context, request));

templates/stock/add_dispatch.html
<!DOCTYPE html>
<html lang="en">
<head>{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Dispatch Item</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="col-lg-6 col-lg-offset-3">
        <h2>Dispatch Item </h2>
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="col-lg-4 col-lg-offset-3">
     <select class="selectpicker" id="item" name="stock_id" onchange="update_item_fields(this.value)">
                    <option value="">Select Stock Item</option>
              {% for stock_item in stock_items %}
                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
              {% endfor %}
     </select>
    </div>
    <form method="post" action="{% url 'stock:dispatch_item' %}" class="col-lg-6 col-lg-offset-3" >
        {% csrf_token %}
        <div class="form-group">

            <label for="name">Item Name</label>
            <input type="text" name="name" class="form-control" value="{% if stock %}{{ stock.name }}
            {% endif %}" readonly>
            <label for="code">Item Code</label>
            <input type="text" name="code" class="form-control" value="{% if stock %}{{ stock.id }}
            {% endif %}" readonly>
            <label for="quantity">Quantity</label>
            <input type="number" step="any" id="quantity" class="form-control" name="quantity" placeholder="Enter Quantity here">
            <label for="rate">Rate</label>
            <input type="number" step="any" id="rate" class="form-control" name="rate" placeholder="Enter rate  here">
            <label for="amount">Amount</label>
            <input type="number" step="any" id="amount" class="form-control" name="amount" placeholder="Enter Amount" onclick="update_amount()">
            <label for="dispatch_to">Dispatch To</label>
            <input type="text"  class="form-control" name="dispatched_to" placeholder="Enter Dispatch To">
            <div class="form-group">
              <label for="comment">Comment:</label>
              <textarea class="form-control" rows="5" id="comment" name="comment"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>

</body>
</html>


<script>
    function update_amount() {
        var rate = document.getElementById('quantity')
        var quantity = document.getElementById('rate')
        var amount = document.getElementById('amount')
        amount.value = rate.value*quantity.value
    }

    function update_item_fields(item_id){

        window.location.href = {% url 'stock:index' %}+'dispatch/'+item_id;

    }



</script>

templates/stock/add_item.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Item</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="col-lg-6 col-lg-offset-3">
        <h2>Add Stock Item </h2>
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form method="post" action="{% url 'stock:add' %}" class="col-lg-6 col-lg-offset-3" >
        {% csrf_token %}
        <div class="form-group">
            <label for="stock_name">Stock Name</label>
            <input type="text" class="form-control" name="stock_name" placeholder="Enter Stock name here">
            <label for="stock_identifier">Stock Identifier</label>
            <input type="text" class="form-control" name="stock_identifier" placeholder="Enter Stock Identifier here">
            <label for="stock_company">Stock Company</label>
            <input type="text"  class="form-control" name="stock_company" placeholder="Enter Stock Company">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>

</body>
</html>

templates/stock/add_returned.html
<!DOCTYPE html>
<html lang="en">
<head>{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Item</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="col-lg-6 col-lg-offset-3">
        <h2>Return Goods  </h2>
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="col-lg-4 col-lg-offset-3">
     <select class="selectpicker" id="item" name="stock_id" onchange="update_item_fields(this.value)">
                    <option value="">Select Stock Item</option>
              {% for stock_item in stock_items %}
                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
              {% endfor %}
     </select>
    </div>
    <form method="post" action="{% url 'stock:return_item' %}" class="col-lg-6 col-lg-offset-3" >
        {% csrf_token %}
        <div class="form-group">

            <label for="name">Item Name</label>
            <input type="text" name="name" class="form-control" value="{% if stock %}{{ stock.name }}
            {% endif %}" readonly>
            <label for="code">Item Code</label>
            <input type="text" name="code" class="form-control" value="{% if stock %}{{ stock.id }}
            {% endif %}" readonly>
            <label for="quantity">Quantity</label>
            <input type="number" step="any" id="quantity" class="form-control" name="quantity" placeholder="Enter Quantity here">
            <label for="returned_by">Returned By</label>
            <input type="text"  class="form-control" name="returned_by" placeholder="Enter Returned By Name">
            <label for="damaged">Damaged</label>
            <input type="checkbox" name="damaged" >
            <div class="form-group">
              <label for="comment">Comment:</label>
              <textarea class="form-control" rows="5" id="comment" name="comment"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>

</body>
</html>


<script>
    function update_amount() {
        var rate = document.getElementById('quantity')
        var quantity = document.getElementById('rate')
        var amount = document.getElementById('amount')
        amount.value = rate.value*quantity.value
    }

    function update_item_fields(item_id){

        window.location.href = {% url 'stock:index' %}+'return_item/'+item_id;

    }



</script>

templates/stock/add_stock.html
<!DOCTYPE html>
<html lang="en">
<head>{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Item</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="col-lg-6 col-lg-offset-3">
        <h2>Add In Stock  </h2>
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="col-lg-4 col-lg-offset-3">
     <select class="selectpicker" id="item" name="stock_id" onchange="update_item_fields(this.value)">
                    <option value="">Select Stock Item</option>
              {% for stock_item in stock_items %}
                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
              {% endfor %}
     </select>
    </div>
    <form method="post" action="{% url 'stock:add_in_stock' %}" class="col-lg-6 col-lg-offset-3" >
        {% csrf_token %}

        <div class="form-group">

            <label for="name">Item Name</label>
            <input type="text" name="name" class="form-control" value="{% if stock %}{{ stock.name }}
            {% endif %}" readonly>
            <label for="code">Item Code</label>
            <input type="text" name="code" class="form-control" value="{% if stock %}{{ stock.id }}
            {% endif %}" readonly>
            <label for="quantity">Quantity</label>
            <input type="number" step="any" id="quantity" class="form-control" name="quantity" placeholder="Enter Quantity here">
            <label for="rate">Rate</label>
            <input type="number" step="any" id="rate" class="form-control" name="rate" placeholder="Enter rate  here">
            <label for="amount">Amount</label>
            <input type="number" step="any" id="amount" class="form-control" name="amount" placeholder="Enter Amount" onclick="update_amount()">
            <label for="received_from">Received From</label>
            <input type="text"  class="form-control" name="received_from" placeholder="Enter Received From">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>

</body>
</html>


<script>
    function update_amount() {
        var rate = document.getElementById('quantity')
        var quantity = document.getElementById('rate')
        var amount = document.getElementById('amount')
        amount.value = rate.value*quantity.value
    }

    function update_item_fields(item_id){

        window.location.href = {% url 'stock:index' %}+'receive/'+item_id;

    }



</script>

templates/stock/dispached.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Items</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <br>
        <div class="col-lg-4 col-lg-offset-4">
            <h2>Dispatched Goods</h2>
        </div>
    <br>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'stock:dispatched' %}" class="form-inline col-lg-11 col-lg-offset-1" >
        <div class="form-group">
          <label for="item">Select Item:</label>
          <select class="selectpicker" id="item" name="stock_id">
              {% for stock_item in stock_items %}
                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
              {% endfor %}
          </select>
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>
<div class="clearfix"></div>
<br>
<div class="table-responsive col-lg-10 col-lg-offset-1">
<table  border="1" about="Stock" class="table" >
    <thead>
        <td><br>S.N</td>
        <td><b>Item Name</b></td>
        <td><b>Item identifier</b></td>
        <td><b>Date</b></td>
        <td><b>Quantity</b></td>
        <td><b>Rate</b></td>
        <td><b>Amount</b></td>
        <td><b>Comment</b></td>
        <td><b>Dispatched To</b></td>
        <td><b>Actions</b></td>
    </thead>

    <tbody>
        {% if items %}
            {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{item.code.name }}</td>
                    <td>{{item.code.identifier }}</td>
                    <td>{{item.created_at }}</td>
                    <td>{{item.quantity }}</td>
                    <td>{{item.rate }}</td>
                    <td>{{item.amount }}</td>
                    <td>{{item.comment }}</td>
                    <td>{{item.dispatched_to }}</td>
                    <td>
                        <div class="btn-group">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="{{stock.id }}">Add Stock</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <div class="alert alert-info" role="alert"><p>No Stock Dispatched.</p></div>

        {% endif %}
    </tbody>
</table>
</div>

</body>
</html>

templates/stock/incoming_item.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Items</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <br>
    <br>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'stock:received' %}" class="form-inline col-lg-11 col-lg-offset-1" >
        <div class="form-group">
          <label for="item">Select Item:</label>
          <select class="selectpicker" id="item" name="stock_id">
              {% for stock_item in stock_items %}
                    <option value="{{ stock_item.id }}">{{ stock_item.name }}</option>
              {% endfor %}
          </select>
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>
<div class="clearfix"></div>
<br>
<div class="table-responsive col-lg-10 col-lg-offset-1">
<table  border="1" about="Stock" class="table" >
    <thead>
        <td><br>S.N</td>
        <td><b>Item Name</b></td>
        <td><b>Item identifier</b></td>
        <td><b>Date</b></td>
        <td><b>Quantity</b></td>
        <td><b>Rate</b></td>
        <td><b>Amount</b></td>
        <td><b>Actions</b></td>
    </thead>

    <tbody>
        {% if items %}
            {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{item.code.identifier }}</td>
                    <td>{{item.code.company }}</td>
                    <td>{{item.created_at }}</td>
                    <td>{{item.quantity }}</td>
                    <td>{{item.rate }}</td>
                    <td>{{item.amount }}</td>
                    <td>
                        <div class="btn-group">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="{{stock.id }}">Add Stock</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <div class="alert alert-info" role="alert"><p>No Stock.</p></div>

        {% endif %}
    </tbody>
</table>
</div>

</body>
</html>

templates/stock/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/stock/list_stock.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Items</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <br>
    <br>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'stock:index' %}" class="form-inline col-lg-11 col-lg-offset-1" >
    <div class="form-group">
    <label for="Stock_name">Stock Name</label>
    <input type="text" class="form-control" name="stock_name" placeholder="Enter Stock Name here">
    <button type="submit" class="btn btn-default">Submit</button>
  </div>

</form>
<div class="clearfix"></div>
<br>
<div class="table-responsive col-lg-10 col-lg-offset-1">
<table  border="1" about="Stock" class="table" >
    <thead>
        <td><b>Stock Name</b></td>
        <td><b>Stock identifier</b></td>
        <td><b>Stock Company</b></td>
        <td><b>Actions</b></td>
    </thead>

    <tbody>
        {% if stock_list %}
            {% for stock in stock_list %}
                <tr>
                    <td>{{stock.name }}</td>
                    <td>{{stock.identifier }}</td>
                    <td>{{stock.company }}</td>
                    <td>
                       <!-- Single button -->
                        <div class="btn-group">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'stock:add_in_stock' stock.id %}">Add Stock</a></li>
                            <li><a href="{% url 'stock:dispatch_item' stock.id %}">Dispatch</a></li>
                            <li><a href="{% url 'stock:return_item' %}">Return</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <div class="alert alert-info" role="alert"><p>No Stock.</p></div>

        {% endif %}
    </tbody>
</table>
</div>

</body>
</html>