Cheque/urls.py
from django.conf.urls import url

from . import views

app_name = 'cheque'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^success/$', views.success, name='success'),
    # url(r'^list/$', views.list , name='list'),
    # #ex: /polls/5/
    # url(r'^(?P<question_id>[0-9]+)/$',views.detail , name='detail'),
    # # ex: /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    #  ex: /polls/5/vote/
    url(r'^save/$', views.save, name='save'),
]

Sales/urls.py
from django.conf.urls import url

from . import views

app_name = 'sales'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^makeinvoice/$', views.make_invoice, name='make_invoice'),
    url(r'^edit/(?P<invoice_id>(\d+))/$',views.edit, name='edit_invoice'),
    url(r'^edit/(?P<invoice_id>)/$', views.edit, name='edit_invoice'),
    url(r'^invoice/list/$', views.list_invoice, name='list_invoice'),
    # url(r'^dispatch/(?P<item_id>(\d+))/$',views.dispatch , name='dispatch_item')

    # url(r'^save/$', views.save, name='save'),
]

# url(r'^list/$', views.list , name='list'),
# #ex: /polls/5/
# url(r'^(?P<question_id>[0-9]+)/$',views.detail , name='detail'),
# # ex: /polls/5/results/
# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#  ex: /polls/5/vote/

hamroproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = (
    url(r'^stock/', include('Stock.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^cheque/', include('Cheque.urls')),
    url(r'^sales/', include('Sales.urls')),
    url(r'^admin/', admin.site.urls),
)

Cheque/models.py
from __future__ import unicode_literals

from django.db import models

class Cheque(models.Model):
    number = models.CharField(max_length=50)
    date = models.DateField(auto_now=True)
    name = models.CharField(max_length=100)
    amount = models.FloatField()
    exchanged = models.BooleanField(default=False)
    remark = models.TextField()
    issued = models.BooleanField(default=False)
    brought_by = models.CharField(max_length=100, null=True)
    assigned_to = models.CharField(max_length=100)
    bank = models.CharField(max_length=200)
    bank_branch = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now=True)

    @staticmethod
    def save_cheque(cheque_data):

        cheque = Cheque()

        cheque.name = cheque_data['cheque_name']
        cheque.amount = cheque_data['cheque_amount']
        cheque.date = cheque_data['cheque_date']
        cheque.number = cheque_data['cheque_number']
        cheque.remark = cheque_data['cheque_remark']

        cheque.save()


# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

Cheque/views.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.template import loader

from Cheque.models import Cheque

def success(request):
    template = loader.get_template('cheque/index.html')
    context = {

    }
    return HttpResponse(template.render(context, request));


def save(request):
    cheque_data = {
                    'cheque_name':request.POST['cheque_name'],
                    'cheque_amount':request.POST['cheque_amount'],
                    'cheque_date' : request.POST['cheque_date'],
                    'cheque_number' : request.POST['cheque_number'],
                    'cheque_remark' :request.POST['cheque_remark'],
                   }
    Cheque.save_cheque(cheque_data)

    return HttpResponseRedirect(reverse('cheque:list'));

def index(request):

    number = request.GET['cheque_number'] if request.GET else ''
    name = request.GET['cheque_name'] if request.GET else ''
    date_search = request.GET['cheque_date'] if request.GET else ''
    cheque_list = Cheque.objects.filter(number__icontains=number.strip(), name__icontains=name.strip())
    if date_search != '':
        cheque_list = cheque_list.filter(date__exact=date_search)


    template = loader.get_template('cheque/list.html')
    context = {
        'cheque_list': cheque_list,
    }
    return HttpResponse(template.render(context, request));

templates/cheque/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>


<h1> CHEQUE ENTRY FORM</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'cheque:save' %}" method="post">
{% csrf_token %}
<input type="text" name="cheque_name" placeholder="Enter Cheque name"><br>
<input type="text" name="cheque_number" placeholder="Enter Cheque Number"><br>
<input type="date" name="cheque_date"><br>
    <input type="text" name="cheque_remark" placeholder="Enter remark"><br>
    <input type="number" name="cheque_amount" placeholder="Enter Cheque Amount"><br>
<input type="submit" value="Save" />
</form>

</body>

</html>

templates/cheque/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>List of Cheque</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="col-lg-4 col-lg-offset-3" style="margin-bottom: 2%">
    <h2> List Of Available Cheques </h2>
</div>
<br>

<form action="{% url 'cheque:index' %}" class="form-inline col-lg-11 col-lg-offset-1" >
    <div class="form-group">
    <label for="cheque_number">Cheque Number</label>
    <input type="text" class="form-control" name="cheque_number" placeholder="Enter cheque number here">
    <label for="cheque_name">Cheque Name</label>
    <input type="text" class="form-control" name="cheque_name" placeholder="Enter cheque name here">
    <label for="cheque_date">Cheque Date</label>
    <input type="date"  class="form-control" name="cheque_date" placeholder="Date">
    <button type="submit" class="btn btn-default">Submit</button>
  </div>

</form>
<div class="clearfix"></div>
<br>
<div class="table-responsive col-lg-10 col-lg-offset-1">
<table  border="1" about="Cheques" class="table" >
    <thead>
        <td><b>Cheque Number</b></td>
        <td><b>Cheque Name</b></td>
        <td><b>Cheque Date</b></td>
        <td><b>Cheque Amount</b></td>
        <td><b>Assigned To</b></td>
        <td><b>Action</b></td>
    </thead>

    <tbody>
        {% if cheque_list %}
            {% for cheque in cheque_list %}
                <tr>
                    <td>{{cheque.number }}</td>
                    <td>{{cheque.name }}</td>
                    <td>{{cheque.date }}</td>
                    <td>{{cheque.amount }}</td>
                    <td>{{cheque.assigned_to }}</td>
                    <td>
                       <!-- Single button -->
                        <div class="btn-group">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        {% else %}
            <p>No Cheques are available.</p>
        {% endif %}
    </tbody>
</table>
</div>


</body>
</html>